googlemaps.api:
  key: AIzaSyBEYnFNHhwoPzUgJo-n5bVCjGbMdk68OVA
  base_url: https://maps.googleapis.com/maps/api

placesapi:
  base_url: ${googlemaps.api.base_url}/place
  displayedFields: formatted_address,name,geometry/location,types

geocodeapi:
  base_url: ${googlemaps.api.base_url}/geocode



logging.level.org.springify.placesapi.accessors: DEBUG
